image: ubuntu:17.04

cache:
  paths:
  - builds

.build_script: &build_script
  script:
    - cd generated
    - ./regenerate.sh
    - cd ..
    - mkdir -p ${BUILD_PATH}
    - cd ${BUILD_PATH}
    - echo Generating makefiles
    - cmake ../..
    - echo Compiling all sources
    - make

build_ubuntu_17.04_g++:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y g++ cmake protobuf-compiler libprotobuf-dev libspatialite-dev
    - export BUILD_PATH="builds/build_ubuntu_17.04_g++"
  <<: *build_script

build_ubuntu_17.04_clang:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y clang cmake protobuf-compiler libprotobuf-dev libspatialite-dev
    - export BUILD_PATH="builds/build_ubuntu_17.04_clang"
  <<: *build_script

test_ubuntu_17.04_g++:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y libprotobuf-dev libspatialite-dev
  script:
    - cd builds/build_ubuntu_17.04_g++
    - test/tests

test_ubuntu_17.04_clang:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y libprotobuf-dev libspatialite-dev
  script:
    - cd builds/build_ubuntu_17.04_clang
    - test/tests

